import { Viewport } from "next";
import "./styles/global.css";
import styles from "./styles/RootLayout.module.css";
import Link from "next/link";
import { usePathname } from "next/navigation";

export const metadata = {
  title: 'Movie App',
  description: 'Generated by Next.js',
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false
};

function RootLayout({children}: {children: React.ReactNode}){
  return (
    <html>
      <body className={styles.Wrapper}>
        <div className={styles.Title}>
          <Link href={"/"}>Movie App</Link>
        </div>
        <div className={styles.MainContents}>
          {children}
        </div>
      </body>
    </html>
  )
};

export default RootLayout;